### ISSUE TITLE
Problem with loading models and vae

### ISSUE THREAD

**Issue by sanjay-uzu** [pydn/ComfyUI-to-Python-Extension#29]
![image](https://github.com/pydn/ComfyUI-to-Python-Extension/assets/65504697/5bac75f4-ed3f-45dc-905a-042afa94daa8)
Global Models Cache:
Ckpt:
  [1] taureal (ids: None)
Vae:
  [1] vae-ft-mse-840000-ema-pruned.vae (ids: None)
Traceback (most recent call last):
  File "E:\ComfyUI\workflow_api.py", line 166, in <module>
    main()
  File "E:\ComfyUI\workflow_api.py", line 137, in main
    ksampler_efficient_48 = ksampler_efficient.sample(
  File "E:\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 693, in sample
    globals_cleanup(prompt)
  File "E:\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 209, in globals_cleanup
    id_array = [id for id in tup[-1] if str(id) in prompt.keys()]
  File "E:\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 209, in <listcomp>
    id_array = [id for id in tup[-1] if str(id) in prompt.keys()]
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by pydn** [comment]
This is hard to troubleshoot without the workflow_api.py file and knowledge of the custom node

**Comment by clifftsnug** [comment]
I have encountered the same error. By any chance this is related to the "extra model paths" configuration in comfyui?

**Comment by clifftsnug** [comment]
I discovered the problem being that the generate model name doesnt correct parse '\'. Check if your model name (path) contains backlash. For example if you see

```
 checkpointloadersimple_1 = checkpointloadersimple.load_checkpoint(
            ckpt_name="SDXL\something.safetensors"
        )
```

change it to

```
 checkpointloadersimple_1 = checkpointloadersimple.load_checkpoint(
            ckpt_name="SDXL\\something.safetensors"
        )
```

see if such solves your problem

**Comment by atmaranto** [comment]
If that's the issue, I did fix that bug on [my fork](https://github.com/atmaranto/ComfyUI-SaveAsScript).

**Comment by pydn** [comment]
The current exporter now forwards hidden `prompt` metadata when the target node supports it, which may address the `prompt
  is None` failure reported here.

  I have not rerun this exact workflow, so before closing this I’d like a retest on the current 2.0.0 release. If this is
  still reproducible, please reply with:
  - current ComfyUI version
  - current extension version
  - minimal API workflow export
  - exact custom node/version involved

  Please retest on 2.0.0 and report back.
