### ISSUE TITLE
"TypeError: 'int' object is not subscriptable" when running script

### ISSUE THREAD

**Issue by runshouse** [pydn/ComfyUI-to-Python-Extension#46]
When I run:
!python comfyui_to_python.py     

I get this error:
Traceback (most recent call last):
  File "/content/ComfyUI/ComfyUI-to-Python-Extension/comfyui_to_python.py", line 460, in <module>
    ComfyUItoPython(input_file=input_file, output_file=output_file, queue_size=queue_size)
  File "/content/ComfyUI/ComfyUI-to-Python-Extension/comfyui_to_python.py", line 425, in __init__
    self.execute()
  File "/content/ComfyUI/ComfyUI-to-Python-Extension/comfyui_to_python.py", line 441, in execute
    load_order = load_order_determiner.determine_load_order()
  File "/content/ComfyUI/ComfyUI-to-Python-Extension/comfyui_to_python.py", line 120, in determine_load_order
    self._load_special_functions_first()
  File "/content/ComfyUI/ComfyUI-to-Python-Extension/comfyui_to_python.py", line 156, in _load_special_functions_first
    class_def = self.node_class_mappings[self.data[key]['class_type']]()
TypeError: 'int' object is not subscriptable

Any ideas?

**Comment by pass-pass-pass** [comment]
how did you solve it

**Comment by VanshRana12** [comment]
How did you solve it? Kindly provide some solution for this, Thanks.

**Comment by colian** [comment]
Hi, have you solved it? Look forward for ur reply!
