### ISSUE TITLE
Plugin nodes not working?

### ISSUE THREAD

**Issue by joshnajera** [pydn/ComfyUI-to-Python-Extension#5]
Any idea if this is possible?  I'd love to make a script utilizing controlnet in the workflow, however running the script generator produces an error:

```
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\ComfyUI-to-Python-Extension\comfyui_to_python.py", line 333, in <module>
    main(input, queue_size)
  File "D:\ComfyUI_windows_portable\ComfyUI\ComfyUI-to-Python-Extension\comfyui_to_python.py", line 324, in main
    load_order = determine_load_order(prompt)
  File "D:\ComfyUI_windows_portable\ComfyUI\ComfyUI-to-Python-Extension\comfyui_to_python.py", line 112, in determine_load_order
    class_def = NODE_CLASS_MAPPINGS[data[key]['class_type']]()
KeyError: 'OpenposePreprocessor'
```

**Comment by joshnajera** [comment]
Awesome!   Tested out without plugins and it works!

The one in particular I'm trying to get to work is:
https://github.com/Fannovel16/comfy_controlnet_preprocessors

But another really popular one is this:
https://github.com/ltdrdata/ComfyUI-Impact-Pack

**Comment by pydn** [comment]
Hey @joshnajera, I just pushed support for custom nodes and tested with the Impact Action Pack and SergeSDXL. Update the extension and let me know if you run into any issues with custom nodes.
