### ISSUE TITLE
Support for WD14Tagger?

### ISSUE THREAD

**Issue by yongsuH** [pydn/ComfyUI-to-Python-Extension#54]
Some files of custom nodes is failed to import.
Seems WD14Tagger is not found from the node list.
The work flow was working perfectly in comfyui.

G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\ComfyUI-to-Python-Extension>python comfyui_to_python.py
Total VRAM 22528 MB, total RAM 65349 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : native
VAE dtype: torch.float32
Using pytorch cross attention
Making the "web\extensions\Gemini_Zho" folder
Traceback (most recent call last):
  File "G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\ComfyUI-to-Python-Extension\..\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Gemini\__init__.py", line 17, in <module>
    os.mkdir(extentions_folder)
FileNotFoundError: [WinError 3] the system can't find designate path: 'G:\\comfyui\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\ComfyUI-to-Python-Extension\\web\\extensions\\Gemini_Zho'

Cannot import G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Gemini module for custom nodes: [WinError 3] the system can't find designate path: 'G:\\comfyui\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\ComfyUI-to-Python-Extension\\web\\extensions\\Gemini_Zho'
[JNodes] - INFO - ffmpeg could not be found. Using ffmpeg from imageio-ffmpeg.
Traceback (most recent call last):
  File "G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\ComfyUI-to-Python-Extension\..\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-JNodes\__init__.py", line 2, in <module>
    from .py.prompting_nodes import *
  File "G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-JNodes\py\prompting_nodes.py", line 15, in <module>
    from token_count import *
ModuleNotFoundError: No module named 'token_count'

Cannot import G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-JNodes module for custom nodes: No module named 'token_count'
Traceback (most recent call last):
  File "G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\ComfyUI-to-Python-Extension\..\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 6, in <module>
    from .glob import manager_server
  File "G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 18, in <module>
    import manager_core as core
ModuleNotFoundError: No module named 'manager_core'

Cannot import G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager module for custom nodes: No module named 'manager_core'
(pysssss:WD14Tagger) [ERROR] onnxruntime is required, please check requirements are installed.
Skip G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
[comfyui_controlnet_aux] | INFO -> Using ckpts path: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
### [START] ComfyUI AlekPet Nodes ###
Node -> ArgosTranslateNode [Loading]
Node -> DeepTranslatorNode [Loading]
Node -> ExtrasNode [Loading]
Node -> GoogleTranslateNode [Loading]
Node -> PainterNode [Loading]
Node -> PoseNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 211 nodes successfully.

        "Everything you've ever wanted is on the other side of fear." - George Addair

Import times for custom nodes:
   0.0 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Selector
   0.0 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BRIA_AI-RMBG
   0.0 seconds (IMPORT FAILED): G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Gemini
   0.0 seconds (IMPORT FAILED): G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUi_PromptStylers
   0.0 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IPAnimate
   0.0 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.1 seconds (IMPORT FAILED): G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-JNodes
   0.2 seconds (IMPORT FAILED): G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   1.2 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   8.4 seconds: G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet

Traceback (most recent call last):
  File "G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\ComfyUI-to-Python-Extension\comfyui_to_python.py", line 460, in <module>
    ComfyUItoPython(input_file=input_file, output_file=output_file, queue_size=queue_size)
  File "G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\ComfyUI-to-Python-Extension\comfyui_to_python.py", line 425, in __init__
    self.execute()
  File "G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\ComfyUI-to-Python-Extension\comfyui_to_python.py", line 441, in execute
    load_order = load_order_determiner.determine_load_order()
  File "G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\ComfyUI-to-Python-Extension\comfyui_to_python.py", line 120, in determine_load_order
    self._load_special_functions_first()
  File "G:\comfyui\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\ComfyUI-to-Python-Extension\comfyui_to_python.py", line 156, in _load_special_functions_first
    class_def = self.node_class_mappings[self.data[key]['class_type']]()
KeyError: 'WD14Tagger|pysssss'

**Comment by maxIrvine** [comment]
I'm also having the same manager-core issue... were you able to resolve it?

**Comment by pydn** [comment]
Can you try again using the latest version of ComfyUI-to-Python-Extension? I just tested with WD14Tagger and it worked for me.
