### ISSUE TITLE
ImportError: cannot import name 'init_custom_nodes' from 'nodes' 

### ISSUE THREAD

**Issue by menahem121** [pydn/ComfyUI-to-Python-Extension#60]
my workflows are working but i am always getting this error:

```
(envcomfyui) ubuntu@ip-172-31-27-65:~/ComfyUI/ComfyUI-to-Python-Extension$ python comfyui_to_python.py
Total VRAM 22488 MB, total RAM 15363 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.27.dev844
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA L4 : native
Using xformers cross attention
Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/ComfyUI-to-Python-Extension/comfyui_to_python.py", line 460, in <module>
    ComfyUItoPython(input_file=input_file, output_file=output_file, queue_size=queue_size)
  File "/home/ubuntu/ComfyUI/ComfyUI-to-Python-Extension/comfyui_to_python.py", line 425, in __init__
    self.execute()
  File "/home/ubuntu/ComfyUI/ComfyUI-to-Python-Extension/comfyui_to_python.py", line 434, in execute
    import_custom_nodes()
  File "/home/ubuntu/ComfyUI/ComfyUI-to-Python-Extension/utils.py", line 16, in import_custom_nodes
    from nodes import init_custom_nodes
ImportError: cannot import name 'init_custom_nodes' from 'nodes' (/home/ubuntu/ComfyUI/ComfyUI-to-Python-Extension/../nodes.py)
```

**Comment by menahem121** [comment]
the issue and how to fix it is mentioned here:
https://github.com/atmaranto/ComfyUI-SaveAsScript/issues/7

**Comment by bjorginson** [comment]
@menahem121 Made a small tweak to the script.
https://github.com/pydn/ComfyUI-to-Python-Extension/pull/61

**Comment by pydn** [comment]
Solved with https://github.com/pydn/ComfyUI-to-Python-Extension/pull/70
