### ISSUE TITLE
NameError: name 'load_custom_node' is not defined

### ISSUE THREAD

**Issue by gopi77** [pydn/ComfyUI-to-Python-Extension#64]
Hi

I have converted the image upscale comfyUI workflow to python file. The json & python file as text attached for reference
[workflow_image_upscale_api.json](https://github.com/user-attachments/files/16505622/workflow_image_upscale_api.json)

[workflow_image_upscale_api.py.txt](https://github.com/user-attachments/files/16505661/workflow_image_upscale_api.py.txt)

While running the python file, I got the below error. Please help.

Traceback (most recent call last):
  File "D:\project\GenAI\ComfyUI\ComfyUI-to-Python-Extension\workflow_image_upscale_api.py", line 227, in <module>
    main()
  File "D:\project\GenAI\ComfyUI\ComfyUI-to-Python-Extension\workflow_image_upscale_api.py", line 164, in main
    init_builtin_extra_nodes()
  File "D:\project\GenAI\ComfyUI\ComfyUI-to-Python-Extension\workflow_image_upscale_api.py", line 144, in init_builtin_extra_nodes
    if not load_custom_node(
           ^^^^^^^^^^^^^^^^
NameError: name 'load_custom_node' is not defined

**Comment by pydn** [comment]
What version of ComfyUI-to-Python-Extension were you using to get this output? Was it a fork of this repo? I don't think it is possible to get the output you provided from a version of the repo I maintain.

 The `init_builtin_extra_nodes()` should have never been defined within the script developed by the extension. That function comes from the `nodes` directory in ComfyUI.
