### ISSUE TITLE
doesn't work with CogVideoX and other custom nodes, although they work well in server mode. In addition, the server mode doesn't warn about xformers

### ISSUE THREAD

**Issue by paelpitsi** [pydn/ComfyUI-to-Python-Extension#87]
[2024-10-21 00:21] ** ComfyUI startup time: 2024-10-21 00:21:26.842979
[2024-10-21 00:21] ** Platform: Windows
[2024-10-21 00:21] ** Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
[2024-10-21 00:21] ** Python executable: C:\Users\Pavel\AppData\Local\Programs\Python\Python310\python.exe
[2024-10-21 00:21] ** ComfyUI Path: D:\comfyui\ComfyUI_windows_portable\ComfyUI
[2024-10-21 00:21] ** Log path: D:\comfyui\ComfyUI_windows_portable\ComfyUI\comfyui.log
[2024-10-21 00:21] 
Prestartup times for custom nodes:
[2024-10-21 00:21]    1.4 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-10-21 00:21] 
Total VRAM 12282 MB, total RAM 32694 MB
[2024-10-21 00:21] pytorch version: 2.2.1+cu121
[2024-10-21 00:21] WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.2.1+cu121)
    Python  3.10.11 (you have 3.10.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
[2024-10-21 00:21] xformers version: 0.0.22
[2024-10-21 00:21] Set vram state to: NORMAL_VRAM
[2024-10-21 00:21] Device: cuda:0 NVIDIA GeForce RTX 4070 SUPER : native
[2024-10-21 00:21] Using pytorch cross attention
[2024-10-21 00:21] Could not find the extra_model_paths config file.
[2024-10-21 00:21] [Prompt Server] web root: D:\comfyui\ComfyUI_windows_portable\ComfyUI\web
[2024-10-21 00:21] Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_upscale_model.py", line 3, in <module>
    from spandrel import ModelLoader, ImageModelDescriptor
ModuleNotFoundError: No module named 'spandrel'

[2024-10-21 00:21] Cannot import D:\comfyui\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_upscale_model.py module for custom nodes: No module named 'spandrel'
[2024-10-21 00:21] C:\Users\Pavel\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
[2024-10-21 00:21] Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 18, in <module>
    from diffusers.schedulers import (
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\utils\__init__.py", line 36, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\Pavel\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\__init__.py)

[2024-10-21 00:21] Cannot import D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper module for custom nodes: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\Pavel\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\__init__.py)
[2024-10-21 00:21] Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\__init__.py", line 7, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 3, in <module>
    import gguf
ModuleNotFoundError: No module named 'gguf'

[2024-10-21 00:21] Cannot import D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF module for custom nodes: No module named 'gguf'
[2024-10-21 00:21] Total VRAM 12282 MB, total RAM 32694 MB
[2024-10-21 00:21] pytorch version: 2.2.1+cu121
[2024-10-21 00:21] xformers version: 0.0.22
[2024-10-21 00:21] Set vram state to: NORMAL_VRAM
[2024-10-21 00:21] Device: cuda:0 NVIDIA GeForce RTX 4070 SUPER : native
[2024-10-21 00:21] ### Loading: ComfyUI-Manager (V2.49.2)
[2024-10-21 00:21] ### ComfyUI Revision: 2551 [83f34314] | Released on '2024-08-16'
[2024-10-21 00:21] Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\nodes.py", line 9, in <module>
    from .pyramid_dit import PyramidDiTForVideoGeneration
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\__init__.py", line 1, in <module>
    from .modeling_pyramid_mmdit import PyramidDiffusionMMDiT
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\modeling_pyramid_mmdit.py", line 6, in <module>
    from diffusers.utils.torch_utils import randn_tensor
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\utils\__init__.py", line 36, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\Pavel\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\__init__.py)

[2024-10-21 00:21] Cannot import D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper module for custom nodes: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\Pavel\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\__init__.py)
[2024-10-21 00:21] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-10-21 00:21] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-10-21 00:21] ComfyUI found: D:\comfyui\ComfyUI_windows_portable\ComfyUI
[2024-10-21 00:21] 'D:\comfyui\ComfyUI_windows_portable\ComfyUI' added to sys.path
[2024-10-21 00:21] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-10-21 00:21] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[2024-10-21 00:21] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-10-21 00:21] Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 32, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 10, in <module>
    from modules.upscaler import UpscalerData
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\modules\upscaler.py", line 3, in <module>
    from comfy_extras.nodes_upscale_model import ImageUpscaleWithModel
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_upscale_model.py", line 3, in <module>
    from spandrel import ModelLoader, ImageModelDescriptor
ModuleNotFoundError: No module named 'spandrel'

[2024-10-21 00:21] Cannot import D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: No module named 'spandrel'
[2024-10-21 00:21] 
Import times for custom nodes:
[2024-10-21 00:21]    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
[2024-10-21 00:21]    0.0 seconds (IMPORT FAILED): D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
[2024-10-21 00:21]    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TCD
[2024-10-21 00:21]    0.0 seconds (IMPORT FAILED): D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
[2024-10-21 00:21]    0.0 seconds (IMPORT FAILED): D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper
[2024-10-21 00:21]    0.0 seconds (IMPORT FAILED): D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
[2024-10-21 00:21]    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
[2024-10-21 00:21]    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
[2024-10-21 00:21]    0.1 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-LDSR
[2024-10-21 00:21]    0.1 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-to-Python-Extension
[2024-10-21 00:21]    0.2 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-10-21 00:21]    0.4 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
[2024-10-21 00:21] 
[2024-10-21 00:21] WARNING: some comfy_extras/ nodes did not import correctly. This may be because they are missing some dependencies.

[2024-10-21 00:21] IMPORT FAILED: nodes_upscale_model.py
[2024-10-21 00:21] 
This issue might be caused by new missing dependencies added the last time you updated ComfyUI.
[2024-10-21 00:21] Please do a: pip install -r requirements.txt
[2024-10-21 00:21] 
[2024-10-21 00:21] Traceback (most recent call last):
[2024-10-21 00:21]   File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\testtt.py", line 235, in <module>
[2024-10-21 00:21]     main()
[2024-10-21 00:21]   File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\testtt.py", line 121, in main
[2024-10-21 00:21]     downloadandloadcogvideomodel = NODE_CLASS_MAPPINGS[
[2024-10-21 00:21] KeyError: 'DownloadAndLoadCogVideoModel'

**Comment by Neflux** [comment]
Have you tried installing those missing pip packages?
