### ISSUE TITLE
Can't handle the easy_anything inversed switch

### ISSUE THREAD

**Issue by AuricMists** [pydn/ComfyUI-to-Python-Extension#92]
I get the following issue with this node -
Traceback (most recent call last):
  File "F:\Work\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-to-Python-Extension\__init__.py", line 50, in save_as_script
    ComfyUItoPython(workflow=workflow, output_file=sio)
  File "F:\Work\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-to-Python-Extension\comfyui_to_python.py", line 544, in __init__
    self.execute()
  File "F:\Work\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-to-Python-Extension\comfyui_to_python.py", line 573, in execute
    generated_code = code_generator.generate_workflow(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Work\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-to-Python-Extension\comfyui_to_python.py", line 290, in generate_workflow
    final_code = self.assemble_python_code(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Work\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-to-Python-Extension\comfyui_to_python.py", line 413, in assemble_python_code
    final_code = black.format_str(final_code, mode=black.Mode())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\black\__init__.py", line 1204, in format_str
  File "src\black\__init__.py", line 1218, in _format_str_once
  File "src\black\parsing.py", line 98, in lib2to3_parse
black.parsing.InvalidInput: Cannot parse: 201:80:                       easy_anythinginversedswitch_36 = easy_anythinginversedswitch.switch(index=0, in=get_value_at_index(vaedecodetiled_19, 0), unique_id=9114656933658906489)

**Comment by mbylstra** [comment]
You can try: https://github.com/pydn/ComfyUI-to-Python-Extension/issues/114

**Comment by AuricMists** [comment]
Thanks. My workaround is to disable the node, make any broken connections then patch any resulting code manually, if necessary. Just reporting in case someone is able to fix it.
